<br /><br />
<div id="view-content">
	<p>View script for controller <b>categories</b> and script/action name <b>list</b></p>
</div>

<div class="container">
<table class="table table-hover">
       <?php
       for($j = 0; $j<count($this->categories); $j++){ ?>
    
    <tr>
       
        <td  class="info" width='120px' height='60px'>
            <img src="../category_images/<?php echo $this->categories[$j]['image'];?>" class="img-circle"  width="100" height="50px"/>
            
        </td>
        
        <td  class="danger" >
            <a href="<?php echo $this->baseUrl()?>/forums/list/id/<?php echo $this->categories[$j]['id'];?>" > <?php echo $this->categories[$j]["name"];?> </a>
            
        </td>
        
        
 <td class="success" width='150px'>    
<a href="<?php echo $this->baseUrl()?>/categories/edit/id/<?php echo $this->categories[$j]['id'];?>/e/-2" class="btn btn-success btn-lg" > Edit </a>

</td>

        <td class="warning" width='150px' >    
<a href="<?php echo $this->baseUrl()?>/categories/delete/id/<?php echo $this->categories[$j]['id'];?>/catImg/<?php echo $this->categories[$j]['image'];?>/d/-2" class="btn btn-danger btn-lg" > Delete </a>

</td>


    </tr>
    <?php

}
?>
</table>
</div>