<br /><br />
<div id="view-content">
	<h1>start of user pages</h1>
	<a href="<?php echo $this->baseUrl()."/usrs/list" ?>">List Users</a><br /><br />
	<a href="<?php echo $this->baseUrl()."/users/login" ?>">login Users</a><br /><br />
	<a href="<?php echo $this->baseUrl()."/users/register" ?>">register</a><br /><br />
	<p>View script for controller <b>Users</b> and script/action name <b>index</b></p>
</div>