<html>
    <header>

    </header>
    <body>
        <div class="col-lg-12"> 
            <div class="container">


                <div class="header">
                    <div class="jumbotron">

                        <h3>login</h3>

                        <div class="form-group-lg"></div>

                        <form  method="post" action="" class="form-horizontal">
                            <div class="form-group">

                            </div>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <?php
                                    echo $this->login;
                                    ?> 
                                </div>
                            </div>

                            

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>