<html>
    <header>

    </header>
    <body>
        <div class="col-lg-12"> 
            <div class="container">


                <div class="header">
                    <div class="jumbotron">

                        <center></center><h1 class="col-md-offset-3"  style="color: black"> Forums
                            <br>
                            <small class="col-md-offset-2 "style="color: black; margin-left: 80px;" > login </small></h1>

                        <div class="form-group-lg"></div>

                        <form  method="post" action="" class="form-horizontal">
                            <div class="form-group">

                            </div>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <?php
                                    echo $this->login;
                                    ?> 
                                </div>
                            </div>

                            

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>