<?php echo $this->doctype() ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.css')); ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-theme.css')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery-2.1.3.min.js')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.js')); ?>

<!--    <link href="tooplate_style.css" rel="stylesheet" type="text/css" />-->
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/tooplate_style.css')); ?> 

<script language="javascript" type="text/javascript">
    function clearText(field)
    {
        if (field.defaultValue == field.value)
            field.value = '';
        else if (field.value == '')
            field.value = field.defaultValue;
    }
</script>
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/swfobject/swfobject.js')); ?> 
<!--    <script type="text/javascript" src="scripts/swfobject/swfobject.js"></script>-->

<script type="text/javascript">
    var flashvars = {};
    flashvars.cssSource = <?php echo $this->headLink()->appendStylesheet($this->baseUrl("/css/piecemaker.css")); ?>
    flashvars.xmlSource = "piecemaker.xml";

    var params = {};
    params.play = "true";
    params.menu = "false";
    params.scale = "showall";
    params.wmode = "transparent";
    params.allowfullscreen = "true";
    params.allowscriptaccess = "always";
    params.allownetworking = "all";

    swfobject.embedSWF('piecemaker.swf', 'piecemaker', '960', '500', '10', null, flashvars,
            params, null);

</script>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/ddsmoothmenu.css')); ?> 

<!--    <link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css" />-->
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/jquery.min.js')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/ddsmoothmenu.js')); ?> 

<!--    <script type="text/javascript" src="scripts/jquery.min.js"></script>
    <script type="text/javascript" src="scripts/ddsmoothmenu.js">-->



</script>

<script type="text/javascript">

    ddsmoothmenu.init({
        mainmenuid: "tooplate_menu", //menu DIV id
        orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
        classname: 'ddsmoothmenu', //class added to menu's outer DIV
        //customtheme: ["#1c5a80", "#18374a"],
        contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
    });

</script>

</head>
<body>


    <div id="tooplate_body_wrapper">
        <div id="tooplate_wrapper">

            <div id="tooplate_header">



                <div id="tooplate_menu" class="ddsmoothmenu">
                    <ul>
                        <li><a href="<?php echo $this->baseUrl('/categories/main'); ?>" class="selected">Admin<span></span></a></li>

                        

                        <li><a href="<?php echo $this->baseUrl('/users/register'); ?>">Registration<span></span></a>
                            
                        </li>

                        <li><a href="<?php echo $this->baseUrl('/users/list'); ?>">Users<span></span></a>
                        </li>

                        <li><a href="<?php echo $this->baseUrl('/users/logout'); ?>">Logout<span></span></a>
   
                        </li>
                        <li><a href="#">Contact<span></span></a></li>
                    </ul>

                    <br style="clear: left" />
                </div> <!-- end of tooplate_menu -->
            </div> <!-- end of tooplate_header -->
        </div>
    </div>
    <div >
        <?php echo $this->layout()->content; ?>

    </div>
    <div id="tooplate_footer_wrapper">

        <div id="tooplate_footer">

       
            

            

            <div class="cleaner h40"></div>
            Copyright © 2016 <a href="#">KFE Forums</a>
            <div class="cleaner"></div>

        </div><!--end of tooplate_footer-->
    </div> <!--end of tooplate_footer_wrapper-->
</body>
</html>