<html>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.css'));?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-theme.css')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery-2.1.3.min.js')) ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.js')) ?>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>