<?php echo $this->doctype() ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap.css')); ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-theme.css')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery-2.1.3.min.js')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.js')); ?>

<!--    <link href="tooplate_style.css" rel="stylesheet" type="text/css" />-->
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/tooplate_style.css')); ?> 

<script language="javascript" type="text/javascript">
    function clearText(field)
    {
        if (field.defaultValue == field.value)
            field.value = '';
        else if (field.value == '')
            field.value = field.defaultValue;
    }
</script>
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/swfobject/swfobject.js')); ?> 
<!--    <script type="text/javascript" src="scripts/swfobject/swfobject.js"></script>-->

<script type="text/javascript">
    var flashvars = {};
    flashvars.cssSource = <?php echo $this->headLink()->appendStylesheet($this->baseUrl("/css/piecemaker.css")); ?>
    flashvars.xmlSource = "piecemaker.xml";

    var params = {};
    params.play = "true";
    params.menu = "false";
    params.scale = "showall";
    params.wmode = "transparent";
    params.allowfullscreen = "true";
    params.allowscriptaccess = "always";
    params.allownetworking = "all";

    swfobject.embedSWF('piecemaker.swf', 'piecemaker', '960', '500', '10', null, flashvars,
            params, null);

</script>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/ddsmoothmenu.css')); ?> 

<!--    <link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css" />-->
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/jquery.min.js')); ?> 
<?php echo $this->headScript()->prependFile($this->baseUrl('/scripts/ddsmoothmenu.js')); ?> 

<!--    <script type="text/javascript" src="scripts/jquery.min.js"></script>
    <script type="text/javascript" src="scripts/ddsmoothmenu.js">-->



</script>

<script type="text/javascript">

    ddsmoothmenu.init({
        mainmenuid: "tooplate_menu", //menu DIV id
        orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
        classname: 'ddsmoothmenu', //class added to menu's outer DIV
        //customtheme: ["#1c5a80", "#18374a"],
        contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
    });

</script>

</head>
<body>


    <div id="tooplate_body_wrapper">
        <div id="tooplate_wrapper">

            <div id="tooplate_header">



                <div id="tooplate_menu" class="ddsmoothmenu">
                    <ul>
                        <li><a href="<?php echo $this->baseUrl('/categories/main'); ?>" class="selected">Admin<span></span></a></li>

                        <li><a href="<?php echo $this->baseUrl('/users/login'); ?>">Login<span></span></a>
                            <ul>
                                <li><a href="#">Sub menu 1</a></li>
                                <li><a href="#">Sub menu 2</a></li>
                                <li><a href="#">Sub menu 3</a></li>
                            </ul>
                        </li>

                        <li><a href="<?php echo $this->baseUrl('/users/register'); ?>">Registration<span></span></a>
                            <ul>
                                <li><a href="#">Sub menu 1</a></li>
                                <li><a href="#">Sub menu 2</a></li>
                                <li><a href="#">Sub menu 3</a></li>
                                <li><a href="#">Sub menu 4</a></li>
                                <li><a href="#">Sub menu 5</a></li>
                            </ul>
                        </li>

                        <li><a href="#">Blog<span></span></a></li>

                        <li><a href="#">Contact<span></span></a></li>
                    </ul>

                    <br style="clear: left" />
                </div> <!-- end of tooplate_menu -->
            </div> <!-- end of tooplate_header -->
        </div>
    </div>
    <div >
        <?php echo $this->layout()->content; ?>

    </div>
    <div id="tooplate_footer_wrapper">

        <div id="tooplate_footer">

            <div class="col_w240">
                <h5>Recent Posts</h5>
                <ul class="footer_link">
                    <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="#">Cras ut ultricies sem</a></li>
                    <li><a href="#">Aliquam erat volutpat</a></li>
                    <li><a href="#">Ut porta lacus at mattis</a></li>
                    <li><a href="#">Maecenas vel lacus id lacus</a></li>
                </ul>
            </div>

            <div class="col_w240">
                <h5>Recent Comments</h5>
                <ul class="footer_link">
                    <li><a href="#">James</a> on <a href="#">Mauris quam nibh</a></li>
                    <li><a href="#">Johnson</a> on <a href="#">Curabitur imperdiet lacus</a></li>
                    <li><a href="#">Nickey</a> on <a href="#">Donec tempor sagittis</a></li>
                    <li><a href="#">Smith</a> on <a href="#">Vestibulum porttitor eleifend</a></li>
                    <li><a href="#">George</a> on <a href="#">eNulla neque justo</a></li>
                </ul>
            </div>

            <div class="col_w240">
                <h5>Blogroll</h5>
                <ul class="footer_link">
                    <li><a href="#">Class aptent taciti</a></li>
                    <li><a href="#">Donec aliquam lorem</a></li>
                    <li><a href="#">Phasellus rhoncus</a></li>
                    <li><a href="#">Fusce tempor magna</a></li>
                    <li><a href="#">Suspendisse et quam</a></li>
                </ul>
            </div>

            <div class="col_w240">
                <h5>Social Links</h5>
                <ul class="footer_link">
                    <li><a href="#" class="facebook social">Facebook</a></li>
                    <li><a href="#" class="linkedin social">Linkedin</a></li>
                    <li><a href="#" class="myspace social">Myspace</a></li>
                    <li><a href="#" class="youtube social">Youtube</a></li>
                    <li><a href="#" class="vimeo social">Vimeo</a></li>
                </ul>
            </div>

            <div class="cleaner h40"></div>
            Copyright © 2048 <a href="#">Company Name</a>
            <div class="cleaner"></div>

        </div><!--end of tooplate_footer-->
    </div> <!--end of tooplate_footer_wrapper-->
</body>
</html>