<head>
    <style>
        .container{
            max-width: 800px;
            margin: 0 auto;
        }
        .container_thread{
            max-width: 800px;
            margin: 0 auto;
        }

        img{
            width: 70px;
            height: 70px;
        }
        .profile_pic{
            border-style: solid;
            border-width: 1px;
            width: 72px;
            height: 72px;
            float: left;
            margin-right: 20px;
        }
        .profile_info{
            width: 100px;
            margin-right: 20px;
            margin-top: 15px;
            display: inline;
        }
        .body{
 
            margin-left: 95px;
            max-width: 600px;
            word-wrap:break-word;

        }
        button{
            margin-left: 100px;
        }
        .date{
            float: right;
        }
    </style>
</head>
<br /><br />
<div id="view-content">
    <div class="container_thread">
        <table class="table table-striped">
            <tr>
                <td  class="danger"><?php
                    $user_model = new Application_Model_Users();
                    $user = $user_model->getUserById($this->thread ["user_id"]);
                    for($i = 0; $i<count($this->user); $i++){
                    echo "<div class='profile_pic'><img src='" . $this->baseUrl() . "../profile_images/{$user[0]['image']}'></img></div>";
                    echo "<div class='profile_info'>" . $user[i]['name'] . "<br>" . "</div>";
                    echo "<div class='date'>" . $this->thread ['date'] . "</div>";
                    }?> </td>
            </tr>
            <tr>
                <td class="warning"><?php
                    echo "<div>" . $this->thread ["title"] . "<br>" . $this->thread ["body"] . "<br>"
                    . "<a href='{$this->baseUrl()}/threads/edit/id/{$this->thread ['id']}'>Edit</a>&nbsp &nbsp "
                    . "<a href='{$this->baseUrl()}/threads/delete/id/{$this->thread ['id']}/forumId/{$this->thread ['forum_id']}'>Delete</a> </div>";
                    ?> </td>
            </tr>
        </table> 
    </div>
    <div class="container">
        <table class="table table-striped" style="display:none">
            <tr>
                <td  class="info"><?php
                    echo "<div class = 'profile_pic'><img id='pic' src =''></img></div>";
                    echo "<div class = 'profile_info'></div>";
                    echo "<div class='date'></div>";
                    echo "<div class = 'body'><span class='body_text'></span><br/><a href ='javascript:;' class='edit-reply'>Edit</a>&nbsp &nbsp "
                    . "<a href ='javascript:;' class='delete-reply'>Delete</a></div>";
                    ?> </td>
            </tr>
        </table>
        <?php
        foreach ($this->replies as $reply) {
            ?>

            <table class="table table-striped" id="reply_<?php echo $reply['id']; ?>">
                <tr>
                    <td  class="info"><?php
                        $user_model = new Application_Model_Users();
                        $user = $user_model->getUserById($reply ["user_id"]);
                        echo "<div class = 'profile_pic'><img id='pic' src = '" . $this->baseUrl() . "/profile_images/{$user[0]['image']}'></img></div>";
                        echo "<div class = 'profile_info'>" . $user[0]['name'] . "<br>" . $user[0]['country'] . "</div>";
                        echo "<div class='date'>" . $reply ['date'] . "</div>";
                        echo "<div class = 'body'><span class='body_text'>" . $reply ['body'] . "</span><br/>"
                        . "<a href ='javascript:;' onclick='editReply({$reply ['id']})' class='edit-reply'>Edit</a>&nbsp &nbsp "
                        . "<a href ='javascript:;' onclick='deleteReply({$reply ['id']})' class='delete-reply'>Delete</a>"
                        . "</div>";
                        ?> </td>
                </tr>
            </table>

            <?php
        }
        ?>

        <div id="addReplayForm"></div>
    </div>

</div>